# Generated by Django 5.2.4 on 2025-07-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emenitites',
            new_name='Tag',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='emenities',
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='listing.tag'),
        ),
    ]
